server:
  port: 8082
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456789
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

validation:
  regularExpresion: ^(.+)@(\\S+)$
